### ISSUE TITLE
《进程相关-process》一文中有死链

### ISSUE THREAD

**Issue by zhulin2609** [chyingp/nodejs-learning-guide#1]
[进程相关-process](https://github.com/chyingp/nodejs-learning-guide/blob/master/%E6%A8%A1%E5%9D%97/process.md)
![image](https://cloud.githubusercontent.com/assets/6648640/26663484/852d272a-46bd-11e7-9172-897ca098d558.png)
[Understanding process.nextTick()](https://howtonode.org/understanding-process-next-tick) 这篇文章502了 
不过这里有一篇译文：[理解 Node.js 里的 process.nextTick()](https://www.oschina.net/translate/understanding-process-next-tick)

**Comment by chyingp** [comment]
@zhulin2609 链接已经复活，目测网站中间挂过 [\奸笑]

**Comment by zhulin2609** [comment]
哈哈 那就close掉这个issue吧！

**Comment by chyingp** [comment]
@zhulin2609 这就是bug延期解决的威力 👉
