### ISSUE TITLE
在app.js里添加了Access-Control-Allow-Origin还是有跨域问题

### ISSUE THREAD

**Issue by wangliangdong** [chyingp/nodejs-learning-guide#17]

**Comment by chyingp** [comment]
@wangliangdong 更详细点的描述？

**Comment by wangliangdong** [comment]
> @wangliangdong 更详细点的描述？

对不起没描述太清楚，我设置了"Access-Control-Allow-Origin", "*"发现还是有跨域问题，然后加了"Access-Control-Allow-Methods", "PUT,POST,GET,DELETE,OPTIONS"，就好了
