### ISSUE TITLE
怎么部署到服务器？

### ISSUE THREAD

**Issue by william-xue** [chyingp/nodejs-learning-guide#2]
我部署过PHP程序 用的mysql。node比较陌生

**Comment by MiYogurt** [comment]
本地怎么运行，服务器就怎么运行。最多加个pm2 跟 nginx。

**Comment by chyingp** [comment]
@william-xue 

1、服务端安装node环境
2、将项目打包上传服务端
3、安装项目依赖（如需要）
4、运行
